# Generated by Django 6.0.4 on 2026-04-15 18:26

import contratos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='nombre_orig_pdf',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='archivo_pdf',
            field=models.FileField(upload_to=contratos.models.ruta_pdf),
        ),
    ]
