# Generated by Django 6.0.4 on 2026-04-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_contrato_nombre_orig_pdf_alter_contrato_archivo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='cliente',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(choices=[('ALQUILER', 'Contrato de Alquiler'), ('NDA', 'Acuerdo de Confidencialidad (NDA)')], default='ALQUILER', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='resultado_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
