services:
  app_django:
    build:
      context: .
      dockerfile: app_django/Dockerfile
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: legallens
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    depends_on:
      - db
    command: ["python", "app_django/manage.py", "runserver", "0.0.0.0:8000"]

  ai:
    build:
      context: .
      dockerfile: AI/Dockerfile
    ports:
      - "8002:8001"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: legallens
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - "80:80"

volumes:
  postgres_data: