version: '3.9'

services:
  app_django:
    build: ./app_django
    ports:
      - "8000:8000"

  AI:
    build: ./AI
    ports:
      - "8001:8001"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: legallens
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nginx:
    image: nginx
    ports:
      - "80:80"